# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jianjundeng/dawn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jianjundeng/dawn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jianjundeng/dawn/CMakeFiles /Users/jianjundeng/dawn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jianjundeng/dawn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./bin/dawn

# Build rule for target.
./bin/dawn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/dawn
.PHONY : ./bin/dawn

# fast build rule for target.
./bin/dawn/fast:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/build
.PHONY : ./bin/dawn/fast

# target to build an object file
src/buffer.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/buffer.o
.PHONY : src/buffer.o

# target to preprocess a source file
src/buffer.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/buffer.i
.PHONY : src/buffer.i

# target to generate assembly for a file
src/buffer.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/buffer.s
.PHONY : src/buffer.s

# target to build an object file
src/connection.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/connection.o
.PHONY : src/connection.o

# target to preprocess a source file
src/connection.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/connection.i
.PHONY : src/connection.i

# target to generate assembly for a file
src/connection.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/connection.s
.PHONY : src/connection.s

# target to build an object file
src/dy_char.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/dy_char.o
.PHONY : src/dy_char.o

# target to preprocess a source file
src/dy_char.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/dy_char.i
.PHONY : src/dy_char.i

# target to generate assembly for a file
src/dy_char.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/dy_char.s
.PHONY : src/dy_char.s

# target to build an object file
src/fdop.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/fdop.o
.PHONY : src/fdop.o

# target to preprocess a source file
src/fdop.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/fdop.i
.PHONY : src/fdop.i

# target to generate assembly for a file
src/fdop.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/fdop.s
.PHONY : src/fdop.s

# target to build an object file
src/hash.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/hash.o
.PHONY : src/hash.o

# target to preprocess a source file
src/hash.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/hash.i
.PHONY : src/hash.i

# target to generate assembly for a file
src/hash.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/hash.s
.PHONY : src/hash.s

# target to build an object file
src/item.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/item.o
.PHONY : src/item.o

# target to preprocess a source file
src/item.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/item.i
.PHONY : src/item.i

# target to generate assembly for a file
src/item.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/item.s
.PHONY : src/item.s

# target to build an object file
src/kqueue.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/kqueue.o
.PHONY : src/kqueue.o

# target to preprocess a source file
src/kqueue.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/kqueue.i
.PHONY : src/kqueue.i

# target to generate assembly for a file
src/kqueue.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/kqueue.s
.PHONY : src/kqueue.s

# target to build an object file
src/list.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/list.o
.PHONY : src/list.o

# target to preprocess a source file
src/list.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/list.i
.PHONY : src/list.i

# target to generate assembly for a file
src/list.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/list.s
.PHONY : src/list.s

# target to build an object file
src/main.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/main.o
.PHONY : src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/main.i
.PHONY : src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/main.s
.PHONY : src/main.s

# target to build an object file
src/malloc.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/malloc.o
.PHONY : src/malloc.o

# target to preprocess a source file
src/malloc.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/malloc.i
.PHONY : src/malloc.i

# target to generate assembly for a file
src/malloc.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/malloc.s
.PHONY : src/malloc.s

# target to build an object file
src/memory.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/memory.o
.PHONY : src/memory.o

# target to preprocess a source file
src/memory.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/memory.i
.PHONY : src/memory.i

# target to generate assembly for a file
src/memory.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/memory.s
.PHONY : src/memory.s

# target to build an object file
src/protocol.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/protocol.o
.PHONY : src/protocol.o

# target to preprocess a source file
src/protocol.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/protocol.i
.PHONY : src/protocol.i

# target to generate assembly for a file
src/protocol.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/protocol.s
.PHONY : src/protocol.s

# target to build an object file
src/queue.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/queue.o
.PHONY : src/queue.o

# target to preprocess a source file
src/queue.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/queue.i
.PHONY : src/queue.i

# target to generate assembly for a file
src/queue.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/queue.s
.PHONY : src/queue.s

# target to build an object file
src/thread.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/thread.o
.PHONY : src/thread.o

# target to preprocess a source file
src/thread.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/thread.i
.PHONY : src/thread.i

# target to generate assembly for a file
src/thread.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/thread.s
.PHONY : src/thread.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ./bin/dawn"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/dy_char.o"
	@echo "... src/dy_char.i"
	@echo "... src/dy_char.s"
	@echo "... src/fdop.o"
	@echo "... src/fdop.i"
	@echo "... src/fdop.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/kqueue.o"
	@echo "... src/kqueue.i"
	@echo "... src/kqueue.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/malloc.o"
	@echo "... src/malloc.i"
	@echo "... src/malloc.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/protocol.o"
	@echo "... src/protocol.i"
	@echo "... src/protocol.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

