# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/dawn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/dawn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/dawn/CMakeFiles /root/dawn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/dawn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./bin/dawn

# Build rule for target.
./bin/dawn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/dawn
.PHONY : ./bin/dawn

# fast build rule for target.
./bin/dawn/fast:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/build
.PHONY : ./bin/dawn/fast

src/buffer.o: src/buffer.c.o
.PHONY : src/buffer.o

# target to build an object file
src/buffer.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/buffer.c.o
.PHONY : src/buffer.c.o

src/buffer.i: src/buffer.c.i
.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/buffer.c.i
.PHONY : src/buffer.c.i

src/buffer.s: src/buffer.c.s
.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/buffer.c.s
.PHONY : src/buffer.c.s

src/common.o: src/common.c.o
.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/common.c.s
.PHONY : src/common.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/config.c.s
.PHONY : src/config.c.s

src/connection.o: src/connection.c.o
.PHONY : src/connection.o

# target to build an object file
src/connection.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/connection.c.o
.PHONY : src/connection.c.o

src/connection.i: src/connection.c.i
.PHONY : src/connection.i

# target to preprocess a source file
src/connection.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/connection.c.i
.PHONY : src/connection.c.i

src/connection.s: src/connection.c.s
.PHONY : src/connection.s

# target to generate assembly for a file
src/connection.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/connection.c.s
.PHONY : src/connection.c.s

src/daemon.o: src/daemon.c.o
.PHONY : src/daemon.o

# target to build an object file
src/daemon.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/daemon.c.o
.PHONY : src/daemon.c.o

src/daemon.i: src/daemon.c.i
.PHONY : src/daemon.i

# target to preprocess a source file
src/daemon.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/daemon.c.i
.PHONY : src/daemon.c.i

src/daemon.s: src/daemon.c.s
.PHONY : src/daemon.s

# target to generate assembly for a file
src/daemon.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/daemon.c.s
.PHONY : src/daemon.c.s

src/dy_char.o: src/dy_char.c.o
.PHONY : src/dy_char.o

# target to build an object file
src/dy_char.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/dy_char.c.o
.PHONY : src/dy_char.c.o

src/dy_char.i: src/dy_char.c.i
.PHONY : src/dy_char.i

# target to preprocess a source file
src/dy_char.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/dy_char.c.i
.PHONY : src/dy_char.c.i

src/dy_char.s: src/dy_char.c.s
.PHONY : src/dy_char.s

# target to generate assembly for a file
src/dy_char.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/dy_char.c.s
.PHONY : src/dy_char.c.s

src/epoll.o: src/epoll.c.o
.PHONY : src/epoll.o

# target to build an object file
src/epoll.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/epoll.c.o
.PHONY : src/epoll.c.o

src/epoll.i: src/epoll.c.i
.PHONY : src/epoll.i

# target to preprocess a source file
src/epoll.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/epoll.c.i
.PHONY : src/epoll.c.i

src/epoll.s: src/epoll.c.s
.PHONY : src/epoll.s

# target to generate assembly for a file
src/epoll.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/epoll.c.s
.PHONY : src/epoll.c.s

src/fdop.o: src/fdop.c.o
.PHONY : src/fdop.o

# target to build an object file
src/fdop.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/fdop.c.o
.PHONY : src/fdop.c.o

src/fdop.i: src/fdop.c.i
.PHONY : src/fdop.i

# target to preprocess a source file
src/fdop.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/fdop.c.i
.PHONY : src/fdop.c.i

src/fdop.s: src/fdop.c.s
.PHONY : src/fdop.s

# target to generate assembly for a file
src/fdop.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/fdop.c.s
.PHONY : src/fdop.c.s

src/hash.o: src/hash.c.o
.PHONY : src/hash.o

# target to build an object file
src/hash.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/hash.c.o
.PHONY : src/hash.c.o

src/hash.i: src/hash.c.i
.PHONY : src/hash.i

# target to preprocess a source file
src/hash.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/hash.c.i
.PHONY : src/hash.c.i

src/hash.s: src/hash.c.s
.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/hash.c.s
.PHONY : src/hash.c.s

src/item.o: src/item.c.o
.PHONY : src/item.o

# target to build an object file
src/item.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/item.c.o
.PHONY : src/item.c.o

src/item.i: src/item.c.i
.PHONY : src/item.i

# target to preprocess a source file
src/item.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/item.c.i
.PHONY : src/item.c.i

src/item.s: src/item.c.s
.PHONY : src/item.s

# target to generate assembly for a file
src/item.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/item.c.s
.PHONY : src/item.c.s

src/kqueue.o: src/kqueue.c.o
.PHONY : src/kqueue.o

# target to build an object file
src/kqueue.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/kqueue.c.o
.PHONY : src/kqueue.c.o

src/kqueue.i: src/kqueue.c.i
.PHONY : src/kqueue.i

# target to preprocess a source file
src/kqueue.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/kqueue.c.i
.PHONY : src/kqueue.c.i

src/kqueue.s: src/kqueue.c.s
.PHONY : src/kqueue.s

# target to generate assembly for a file
src/kqueue.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/kqueue.c.s
.PHONY : src/kqueue.c.s

src/list.o: src/list.c.o
.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i
.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s
.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/list.c.s
.PHONY : src/list.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/main.c.s
.PHONY : src/main.c.s

src/memory.o: src/memory.c.o
.PHONY : src/memory.o

# target to build an object file
src/memory.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/memory.c.o
.PHONY : src/memory.c.o

src/memory.i: src/memory.c.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/memory.c.s
.PHONY : src/memory.c.s

src/my_log.o: src/my_log.c.o
.PHONY : src/my_log.o

# target to build an object file
src/my_log.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/my_log.c.o
.PHONY : src/my_log.c.o

src/my_log.i: src/my_log.c.i
.PHONY : src/my_log.i

# target to preprocess a source file
src/my_log.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/my_log.c.i
.PHONY : src/my_log.c.i

src/my_log.s: src/my_log.c.s
.PHONY : src/my_log.s

# target to generate assembly for a file
src/my_log.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/my_log.c.s
.PHONY : src/my_log.c.s

src/persistence.o: src/persistence.c.o
.PHONY : src/persistence.o

# target to build an object file
src/persistence.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/persistence.c.o
.PHONY : src/persistence.c.o

src/persistence.i: src/persistence.c.i
.PHONY : src/persistence.i

# target to preprocess a source file
src/persistence.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/persistence.c.i
.PHONY : src/persistence.c.i

src/persistence.s: src/persistence.c.s
.PHONY : src/persistence.s

# target to generate assembly for a file
src/persistence.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/persistence.c.s
.PHONY : src/persistence.c.s

src/poll.o: src/poll.c.o
.PHONY : src/poll.o

# target to build an object file
src/poll.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/poll.c.o
.PHONY : src/poll.c.o

src/poll.i: src/poll.c.i
.PHONY : src/poll.i

# target to preprocess a source file
src/poll.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/poll.c.i
.PHONY : src/poll.c.i

src/poll.s: src/poll.c.s
.PHONY : src/poll.s

# target to generate assembly for a file
src/poll.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/poll.c.s
.PHONY : src/poll.c.s

src/protocol.o: src/protocol.c.o
.PHONY : src/protocol.o

# target to build an object file
src/protocol.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/protocol.c.o
.PHONY : src/protocol.c.o

src/protocol.i: src/protocol.c.i
.PHONY : src/protocol.i

# target to preprocess a source file
src/protocol.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/protocol.c.i
.PHONY : src/protocol.c.i

src/protocol.s: src/protocol.c.s
.PHONY : src/protocol.s

# target to generate assembly for a file
src/protocol.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/protocol.c.s
.PHONY : src/protocol.c.s

src/queue.o: src/queue.c.o
.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i
.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s
.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/select.o: src/select.c.o
.PHONY : src/select.o

# target to build an object file
src/select.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/select.c.o
.PHONY : src/select.c.o

src/select.i: src/select.c.i
.PHONY : src/select.i

# target to preprocess a source file
src/select.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/select.c.i
.PHONY : src/select.c.i

src/select.s: src/select.c.s
.PHONY : src/select.s

# target to generate assembly for a file
src/select.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/select.c.s
.PHONY : src/select.c.s

src/statistics.o: src/statistics.c.o
.PHONY : src/statistics.o

# target to build an object file
src/statistics.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/statistics.c.o
.PHONY : src/statistics.c.o

src/statistics.i: src/statistics.c.i
.PHONY : src/statistics.i

# target to preprocess a source file
src/statistics.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/statistics.c.i
.PHONY : src/statistics.c.i

src/statistics.s: src/statistics.c.s
.PHONY : src/statistics.s

# target to generate assembly for a file
src/statistics.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/statistics.c.s
.PHONY : src/statistics.c.s

src/thread.o: src/thread.c.o
.PHONY : src/thread.o

# target to build an object file
src/thread.c.o:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/thread.c.o
.PHONY : src/thread.c.o

src/thread.i: src/thread.c.i
.PHONY : src/thread.i

# target to preprocess a source file
src/thread.c.i:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/thread.c.i
.PHONY : src/thread.c.i

src/thread.s: src/thread.c.s
.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.c.s:
	$(MAKE) -f CMakeFiles/./bin/dawn.dir/build.make CMakeFiles/./bin/dawn.dir/src/thread.c.s
.PHONY : src/thread.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ./bin/dawn"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/daemon.o"
	@echo "... src/daemon.i"
	@echo "... src/daemon.s"
	@echo "... src/dy_char.o"
	@echo "... src/dy_char.i"
	@echo "... src/dy_char.s"
	@echo "... src/epoll.o"
	@echo "... src/epoll.i"
	@echo "... src/epoll.s"
	@echo "... src/fdop.o"
	@echo "... src/fdop.i"
	@echo "... src/fdop.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/kqueue.o"
	@echo "... src/kqueue.i"
	@echo "... src/kqueue.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/my_log.o"
	@echo "... src/my_log.i"
	@echo "... src/my_log.s"
	@echo "... src/persistence.o"
	@echo "... src/persistence.i"
	@echo "... src/persistence.s"
	@echo "... src/poll.o"
	@echo "... src/poll.i"
	@echo "... src/poll.s"
	@echo "... src/protocol.o"
	@echo "... src/protocol.i"
	@echo "... src/protocol.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/select.o"
	@echo "... src/select.i"
	@echo "... src/select.s"
	@echo "... src/statistics.o"
	@echo "... src/statistics.i"
	@echo "... src/statistics.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

